en:
  languageCode: en
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh
  contentDir: content/zh
  title: wjjss.com
  params:
    description: 描述
  menu:
    main:
      - name: 文档
        url: '/doc'
        weight: 10
    doc:
      - name: Home
        url: '/'
        weight: 10
